# Generated by Django 4.2.4 on 2023-08-31 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
